version: 2.1

defaults: &defaults
  working_directory: /tmp/app
  docker:
    - image: cimg/go:1.22.3

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set container destination
          command: |
            touch .destination
            if git describe --exact-match HEAD > /dev/null 2>&1; then
              echo "--destination ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)" | tee .destination
            else
              echo "--no-push" | tee .destination
            fi
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}
            - go-mod-v1
      - run:
          name: Download dependencies
          command: go mod vendor
      - save_cache:
          key: go-mod-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: make lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: make build

  publish:
    <<: *defaults
    docker:
      - image: gcr.io/kaniko-project/executor:v1.23.1-debug
        entrypoint: ""
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build container image
          command: |
            AUTH=$(echo -n "markormesher:${GHCR_PUBLISH_TOKEN}" | base64)
            echo '{"auths":{"ghcr.io":{"auth":"'${AUTH}'"}}}' > /kaniko/.docker/config.json
            /kaniko/executor \
              --verbosity debug \
              --context dir:///tmp/app \
              --ignore-path /tmp/app \
              --dockerfile /tmp/app/Containerfile \
              $(cat .destination)

workflows:
  version: 2
  main:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - lint
            - build
          filters:
            tags:
              only: /.*/
